[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
via_ir = true

# Gas reporting
gas_reports = ["*"]

# Network configurations
[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"

# Etherscan configuration for contract verification (optional)
# [etherscan]
# base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
# base_mainnet = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# Deployment profiles
[profile.deploy]
optimizer = true
optimizer_runs = 1000
via_ir = true